development:
  adapter: postgresql
  database: scale_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: scale_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: scale_production
  pool: 5
  timeout: 5000
